language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=61ffb7c6689c41a642eabd105ba797cec7a82a81bd80e6593d810c60d06844d9
node_js:
  - stable
install:
  - npm i -g typescript typings
  - npm install
before_script:
  - npm run build
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  skip_cleanup: true
  provider: npm

  email: julien.sarazin@me.com
  api_key:
    secure: BloBuKq3UI2UBFegISHnhC/NYkwJH8v7hnZp6vs6ehEKRL8+YR6WydChG4nRqXf8zCxt9haElQRm084pjjMtix8D2H/BVnH/NfHQ/sI6r/Bb/h4JTHKAr/A7Xg/L68fvI6CBThusGZbVH/75e/zSy1IdiBDP127pJPDlVwffWg9FHAKoNFQEjdSsBEFhqGp+1N8S4cuwBbVzEykDb6OT8c78TfSd5B4S/12kN2YpSYwxkkr+uuphnCzR7gn1CG+sOwekh2Hf1vv/OyXnlP81vTXaUOktz9d+be4MlD2ycHABAoIbCDOO2ACuVKixeVlwInWOHBauFpbY+IwvSyFC9sRkezB1+WG6XFC4Ltfl/UxVh2C1Ekr4nBBAxlszw60IoH6lxUkZhFtxkKsJmwg4824w59hOsWdVVKCTxmoKw52xUMnlYfyGJj9lWiPexYCsIuxussiDsfr8QUqFdjvg6FCJNu8SGhw3KlvG3YNkUR9oK7eeHURZBrgmPJE0oO4jvg5dSQaUI/a5oOXY6pncopERf+3GktAnFAGaydlowyD47MgzRUo8nYapc8zz7KYIvvE0CbGow/PheaWesxsOT5556IWkvf3by6CL6hNvgV46E/BizNXIbWSJzxdtKtnyh5oCFFiWTJD2aF+4cAR0nBHNCOF2qeK54IxOtwE7Se0=
  on:
    tags: true
    repo: implicity-healthcare/nest-http
